### ISSUE TITLE
Can't run it successfully

### ISSUE THREAD

**Issue by wzywzy** [anandmuralidhar24/AssimpAndroid#4]
Hi! When I run this project, it reminds me that "couldn't find 'libModelAssimpNative.so'" How can I solve it???

**Comment by kimkulling** [comment]
Just checked the gradle file. When I get it right you need to install the prebuild addimp stuff before.

**Comment by wzywzy** [comment]
Thank you! May you give your email? I want to consult some detailed questions...

**Comment by kimkulling** [comment]
kim.kulling<at>googlemail.com

**Comment by wzywzy** [comment]
Invalid email.........

**Comment by kimkulling** [comment]
Just introduce an @ between the name and google.
