### ISSUE TITLE
how to run it successful?

### ISSUE THREAD

**Issue by Nullifier1571** [anandmuralidhar24/AssimpAndroid#5]
i clone it in macos androidstudio3.1,when i run it it occurrend “can't find stdio.h ” and i cannot find ModelAssimpNative.so in this project，so how it's work?oh, it's to hard for me to use assimp project,i only want to use it to load a .dae file in android device.can you provide a simple dame? very thanks!

**Comment by anandmuralidhar24** [comment]
Hi,
You need to build the project and that will create the .so file. I'm not working on the project anymore and you will need to modify it to load a different file format.
