### ISSUE TITLE
Gradle Sync Fails

### ISSUE THREAD

**Issue by SowmyaN9** [anandmuralidhar24/AssimpAndroid#6]
Hi,
I'm facing gradle sync issue, after opening this project in AS,it asks for plugin update as gradle-experimental:0.7.0-alpha4 is incompatible with the current version of AS and finally gradle needs the file 
https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.2.71/kotlin-stdlib-jdk8-1.2.71.pom and sync fails.
Android Studio version : 3.2.1
Any help would be appreciated!
Thank you!

**Comment by SowmyaN9** [comment]
Hi,
I followed the gradle recommendation for updates and ended up with the above issue... when I use the specified gradle 2.14.1 and gradle-experimental plugin 0.8.0, the app builds and works perfectly!

**Comment by anandmuralidhar24** [comment]
Thanks Sowmya, for resolving this on your own :) 
It's been a long time and I have not updated the build for the project.

**Comment by agGitHub** [comment]
Unable to run this project on Android 2020.3.1 event after change to  gradle 2.14.1 and gradle-experimental plugin 0.8.0. Any idea ? Thanks.

**Comment by anandmuralidhar24** [comment]
> Unable to run this project on Android 2020.3.1 event after change to gradle 2.14.1 and gradle-experimental plugin 0.8.0. Any idea ? Thanks.

Apologies! I've not been maintaining the build and not sure if something has changed in the new version of AndroidStudio. Hope you are able to fix it with the appropriate gradle and plugin versions.
