### ISSUE TITLE
C++ compiler failed while compiling GLContext.cpp.

### ISSUE THREAD

**Issue by robbie2021** [anandmuralidhar24/AssimpAndroid#7]
Hi,
I sync the project successfully, but when i make project, there is a error "C++ compiler failed while compiling GLContext.cpp.".
Could you tell me what's wrong?
Thanks.

**Comment by anandmuralidhar24** [comment]
Hi,
Looks like might be having the wrong version of Android Studio or some other setting might be incorrect since others have not had this problem. Please follow the instructions to compile the code from here: http://www.anandmuralidhar.com/blog/android/assimp/#Get_the_code
